# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Structural interfaces consumed by snapshot-only GMS V1."""

from __future__ import annotations

from typing import Protocol

from gpu_memory_service.common.locks import GrantedLockType

from .protocol import Allocation, Generation


class VMM(Protocol):
    def ensure_initialized(self) -> None: ...

    def synchronize(self) -> None: ...

    def get_allocation_granularity(self, device: int) -> int: ...

    def create_tolerate_oom(self, size: int, device: int) -> tuple[bool, int]: ...

    def release(self, handle: int) -> None: ...

    def export_to_shareable_handle(self, handle: int) -> int: ...

    def import_shareable_handle_close_fd(self, fd: int) -> int: ...

    def address_reserve(self, size: int, granularity: int) -> int: ...

    def address_free(self, va: int, size: int) -> None: ...

    def map(self, va: int, size: int, handle: int) -> None: ...

    def unmap(self, va: int, size: int) -> None: ...

    def set_access(
        self, va: int, size: int, device: int, access: GrantedLockType
    ) -> None: ...

    def runtime_set_device(self, device: int) -> None: ...


class AllocationService(Protocol):
    def begin(self, generation: Generation) -> None: ...

    def allocate(self, owner: str, allocation: Allocation) -> None: ...

    def free(self, owner: str, allocation: Allocation) -> None: ...

    def export(self, owner: str, allocation: Allocation) -> int: ...

    def seal(self, generation: Generation, artifact_id: str) -> None: ...

    def attach(
        self,
        generation: Generation,
        artifact_id: str,
        reader_id: str,
        parameters: tuple[Allocation, ...],
    ) -> None: ...

    def detach(self, generation: Generation, reader_id: str) -> None: ...

    def release_artifact(self, generation: Generation, artifact_id: str) -> None: ...

    def retire(self, generation: Generation) -> None: ...
